### ISSUE TITLE
Improve error handling and stack trace reporting for promise handlers

### ISSUE THREAD

**Issue by stokilo** [stokilo/puppa#7]
Currently elem() and felem() function do not report full stack trace of error, consider example code:

`await elem("#lst-ib", elem => elem2.val('test'));`

in this example 
`elem => elem2.val('test')`

will throw an error: **ReferenceError: elem2 is not defined**

but there is no stack trace to track error source. Target it to implement stack trace like presented below:

```
Could not execute promise handler: ReferenceError: elems is not defined Error
    at elem (file:///D:/projects/puppa/lib/core/puppa.js:32:17)
    at testGoogleSearch (tests/google.js:7:11)
    at runTest (file:///D:/projects/puppa/lib/core/puppa.js:96:19)
    at <anonymous>:1:23
    at <anonymous>:1:36
```

**Comment by stokilo** [comment]
Implemented in 
+ puppa@1.0.19
