### ISSUE TITLE
Improve error handling for main test function call.

### ISSUE THREAD

**Issue by stokilo** [stokilo/puppa#8]
Javascript error thrown from main test function does not contain stacktrace.
Example stack trace for following code:

```
testGoogleSearch = async function (config) {
    nonExistingFunction();
}
```
Result: https://google.com:testGoogleSearch: Failed
`        nonExistingFunction is not defined`

Required:

```
nonExistingFunction is not defined ReferenceError: nonExistingFunction is not defined 
   at testGoogleSearch (tests/google.js:6:5)
   at runTest (file:///D:/projects/puppa/lib/core/puppa.js:94:19)
   at <anonymous>:1:23
   at <anonymous>:1:36
```

**Comment by stokilo** [comment]
Implemented in: + puppa@1.0.20
